Bookstore/Models/DomainModels/Cart.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;

namespace Bookstore.Models
{
    public class Cart
    {
        private const string CartKey = "mycart";
        private const string CountKey = "mycount";

        private List<CartItem> items { get; set; }
        private List<CartItemDTO> storedItems { get; set; }

        private ISession session { get; set; }
        private IRequestCookieCollection requestCookies { get; set; }
        private IResponseCookies responseCookies { get; set; }

        public Cart(HttpContext ctx)
        {
            session = ctx.Session;
            requestCookies = ctx.Request.Cookies;
            responseCookies = ctx.Response.Cookies;
        }

        public void Load(Repository<Book> data)
        {
            items = session.GetObject<List<CartItem>>(CartKey);
            if (items == null) {
                items = new List<CartItem>();
                storedItems = requestCookies.GetObject<List<CartItemDTO>>(CartKey);
            }
            if (storedItems?.Count > items?.Count) {
                foreach (CartItemDTO storedItem in storedItems) {
                    var book = data.Get(new QueryOptions<Book> {
                        Include = "BookAuthors.Author, Genre",
                        Where = b => b.BookId == storedItem.BookId
                    });
                    if (book != null) {
                        var dto = new BookDTO();
                        dto.Load(book);

                        CartItem item = new CartItem {
                            Book = dto,
                            Quantity = storedItem.Quantity
                        };
                        items.Add(item);
                    }
                }
                Save();
            }
        }

        public double Subtotal => items.Sum(i => i.Subtotal);
        public int? Count => session.GetInt32(CountKey) ?? requestCookies.GetInt32(CountKey);
        public IEnumerable<CartItem> List => items;

        public CartItem GetById(int id) => 
            items.FirstOrDefault(ci => ci.Book.BookId == id);

        public void Add(CartItem item) {
            var itemInCart = GetById(item.Book.BookId);
            
            if (itemInCart == null) {
                items.Add(item);
            }
            else {  
                itemInCart.Quantity += 1;
            }
        }

        public void Edit(CartItem item)
        {
            var itemInCart = GetById(item.Book.BookId);
            if (itemInCart != null) {
                itemInCart.Quantity = item.Quantity;
            }
        }

        public void Remove(CartItem item) => items.Remove(item);
        public void Clear() => items.Clear();
        
        public void Save() {
            if (items.Count == 0) {
                session.Remove(CartKey);
                session.Remove(CountKey);
                responseCookies.Delete(CartKey);
                responseCookies.Delete(CountKey);
            }
            else {
                session.SetObject<List<CartItem>>(CartKey, items);
                session.SetInt32(CountKey, items.Count);
                responseCookies.SetObject<List<CartItemDTO>>(CartKey, items.ToDTO());
                responseCookies.SetInt32(CountKey, items.Count);
            }
        }
    }
}

Bookstore/Models/ViewModels/CartViewModel.cs
using System.Collections.Generic;

namespace Bookstore.Models
{
    public class CartViewModel 
    {
        public IEnumerable<CartItem> List { get; set; }
        public double Subtotal { get; set; }
        public RouteDictionary BookGridRoute { get; set; }
    }
}

Bookstore/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class AuthorController : Controller
    {
        private Repository<Author> data { get; set; }
        public AuthorController(BookstoreContext ctx) => data = new Repository<Author>(ctx);

        public IActionResult Index() => RedirectToAction("List");

        public ViewResult List(GridDTO vals)
        {
            string defaultSort = nameof(Author.FirstName);
            var builder = new GridBuilder(HttpContext.Session, vals, defaultSort);
            builder.SaveRouteSegments();

            var options = new QueryOptions<Author> {
                Include = "BookAuthors.Book",
                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection
            };
            if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
                options.OrderBy = a => a.FirstName;
            else
                options.OrderBy = a => a.LastName;

            var vm = new AuthorListViewModel {
                Authors = data.List(options),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.Count)
            };

            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var author = data.Get(new QueryOptions<Author> {
                Include = "BookAuthors.Book",
                Where = a => a.AuthorId == id
            });
            return View(author);
        }
    }
}

Bookstore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private Repository<Book> data { get; set; }
        public CartController(BookstoreContext ctx) => data = new Repository<Book>(ctx);


        private Cart GetCart()
        {
            var cart = new Cart(HttpContext);
            cart.Load(data);
            return cart;
        }

        public ViewResult Index() 
        {
            var cart = GetCart();
            var builder = new BooksGridBuilder(HttpContext.Session);

            var vm = new CartViewModel {
                List = cart.List,
                Subtotal = cart.Subtotal,
                BookGridRoute = builder.CurrentRoute
            };
            return View(vm);
        }

        [HttpPost]
        public RedirectToActionResult Add(int id)
        {
            var book = data.Get(new QueryOptions<Book> {
                Include = "BookAuthors.Author, Genre",
                Where = b => b.BookId == id
            });
            if (book == null){
                TempData["message"] = "Unable to add book to cart.";   
            }
            else {
                var dto = new BookDTO();
                dto.Load(book);
                CartItem item = new CartItem {
                    Book = dto,
                    Quantity = 1  
                };

                Cart cart = GetCart();
                cart.Add(item);
                cart.Save();

                TempData["message"] = $"{book.Title} added to cart";
            }

            var builder = new BooksGridBuilder(HttpContext.Session);
            return RedirectToAction("List", "Book", builder.CurrentRoute);
        }

        [HttpPost]
        public RedirectToActionResult Remove(int id)
        {
            Cart cart = GetCart();
            CartItem item = cart.GetById(id);
            cart.Remove(item);
            cart.Save();

            TempData["message"] = $"{item.Book.Title} removed from cart.";
            return RedirectToAction("Index");
        }
                
        [HttpPost]
        public RedirectToActionResult Clear()
        {
            Cart cart = GetCart();
            cart.Clear();
            cart.Save();

            TempData["message"] = "Cart cleared.";
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            Cart cart = GetCart();
            CartItem item = cart.GetById(id);
            if (item == null)
            {
                TempData["message"] = "Unable to locate cart item";
                return RedirectToAction("List");
            }
            else
            {
                return View(item);
            }
        }

        [HttpPost]
        public RedirectToActionResult Edit(CartItem item)
        {
            Cart cart = GetCart();
            cart.Edit(item);
            cart.Save();

            TempData["message"] = $"{item.Book.Title} updated";
            return RedirectToAction("Index");
        }

        public ViewResult Checkout() => View();
    }
}

Bookstore/Views/Cart/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>
<ul class="list-group">
    <li class="list-group-item bg-danger text-white">
        <h4>Don't roll your own checkout! It isn't secure!</h4>
    </li>
    <li class="list-group-item bg-warning">
        Use a third party payment service, like 
        <a href="https://stripe.com/" target="_blank">Stripe</a> or
        <a href="https://transferwise.com/us" target="_blank">TransferWise</a>. 

        Most are pretty easy to incorporate in to your own web application, and then
        you aren't handling money or trying to store credit card numbers.
    </li>
</ul>

Bookstore/Views/Cart/Edit.cshtml
@model CartItem

@{
    ViewData["Title"] = " | Edit Cart";
}

<h1>Edit Cart Item</h1>
<form asp-action="Edit" method="post">
    <ul class="list-group mb-2">
        <li class="list-group-item">@Model.Book.Title</li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-1">
                    <label>Price:</label>
                </div>
                <div class="col">
                    @Model.Book.Price.ToString("c")
                </div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="form-row">
                <div class="col-1">
                    <label asp-for="Quantity">Quantity:</label>
                </div>
                <div class="col">
                    <select asp-for="Quantity" class="form-control">
                        @for (int i = 1; i <= 10; i++)
                        {
                            <option>@i</option>
                        }
                    </select>
                </div>
            </div>
        </li>
    </ul>
    <input type="hidden" asp-for="Book.BookId" />
    <input type="hidden" asp-for="Book.Title" />

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Index" asp-controller="Cart" class="btn btn-primary">Cancel</a>
</form>

Bookstore/Views/Cart/Index.cshtml
@model CartViewModel

@{
    ViewData["Title"] = " | Cart";
}

<h1>Your Cart</h1>

<form asp-action="Clear" method="post">
    <ul class="list-group mb-4">
        <li class="list-group-item">
            <div class="row">
                <div class="col">
                    Subtotal: @Model.Subtotal.ToString("c")
                </div>
                <div class="col">
                    <div class="float-right">
                        <a asp-action="Checkout" class="btn btn-primary">Checkout</a>
                        <button type="submit" class="btn btn-primary">Clear Cart</button>
                        <a asp-action="List" asp-controller="Book"
                           asp-all-route-data="@Model.BookGridRoute">Back to Shopping</a>
                    </div>
                    
                </div>
            </div>
        </li>
    </ul>
</form>
<form asp-action="Remove" method="post">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Author(s)</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (CartItem item in Model.List)  {
                <tr>
                    <td>
                        <a asp-action="Details" asp-controller="Book"
                           asp-route-id="@item.Book.BookId"
                           asp-route-slug="@item.Book.Title.Slug()">
                            @item.Book.Title
                        </a>
                    </td>
                    <td>
                        @foreach (var keyValuePair in item.Book.Authors) {
                            <p>
                                <a asp-action="Details" asp-controller="Author"
                                   asp-route-id="@keyValuePair.Key"
                                   asp-route-slug="@keyValuePair.Value.Slug()">
                                    @keyValuePair.Value
                                </a>
                            </p>
                        }
                    </td>
                    <td>@item.Book.Price.ToString("c")</td>
                    <td>@item.Quantity</td>
                    <td>@item.Subtotal.ToString("c")</td>
                    <td>
                        <div class="float-right">
                            <a asp-action="Edit" asp-controller="Cart"
                               asp-route-id="@item.Book.BookId"
                               asp-route-slug="@item.Book.Title.Slug()"
                               class="btn btn-primary">Edit</a>
                            <button type="submit" name="id" value="@item.Book.BookId"
                                    class="btn btn-primary">Remove</button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>