Bookstore/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class AuthorController : Controller
    {
        private Repository<Author> data { get; set; }
        public AuthorController(BookstoreContext ctx) => data = new Repository<Author>(ctx);

        public IActionResult Index() => RedirectToAction("List");

        public ViewResult List(GridDTO vals)
        {
            string defaultSort = nameof(Author.FirstName);
            var builder = new GridBuilder(HttpContext.Session, vals, defaultSort);
            builder.SaveRouteSegments();

            var options = new QueryOptions<Author> {
                Include = "BookAuthors.Book",
                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize,
                OrderByDirection = builder.CurrentRoute.SortDirection
            };
            if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
                options.OrderBy = a => a.FirstName;
            else
                options.OrderBy = a => a.LastName;

            var vm = new AuthorListViewModel {
                Authors = data.List(options),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.Count)
            };

            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var author = data.Get(new QueryOptions<Author> {
                Include = "BookAuthors.Book",
                Where = a => a.AuthorId == id
            });
            return View(author);
        }
    }
}

Bookstore/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class BookController : Controller
    {
        private BookstoreUnitOfWork data { get; set; }
        public BookController(BookstoreContext ctx) => data = new BookstoreUnitOfWork(ctx);

        public RedirectToActionResult Index() => RedirectToAction("List");

        public ViewResult List(BooksGridDTO values)
        {
            var builder = new BooksGridBuilder(HttpContext.Session, values, 
                defaultSortField: nameof(Book.Title));

            var options = new BookQueryOptions {
                Include = "BookAuthors.Author, Genre",
                OrderByDirection = builder.CurrentRoute.SortDirection,
                PageNumber = builder.CurrentRoute.PageNumber,
                PageSize = builder.CurrentRoute.PageSize
            };
            options.SortFilter(builder);

            var vm = new BookListViewModel {
                Books = data.Books.List(options),
                Authors = data.Authors.List(new QueryOptions<Author> {
                    OrderBy = a => a.FirstName }),
                Genres = data.Genres.List(new QueryOptions<Genre> {
                    OrderBy = g => g.Name }),
                CurrentRoute = builder.CurrentRoute,
                TotalPages = builder.GetTotalPages(data.Books.Count)
            };

            return View(vm);
        }

        public ViewResult Details(int id)
        {
            var book = data.Books.Get(new QueryOptions<Book> {
                Include = "BookAuthors.Author, Genre",
                Where = b => b.BookId == id
            });
            return View(book);
        }

        [HttpPost]
        public RedirectToActionResult Filter(string[] filter, bool clear = false)
        {
            var builder = new BooksGridBuilder(HttpContext.Session);

            if (clear) {
                builder.ClearFilterSegments();
            }
            else {
                var author = data.Authors.Get(filter[0].ToInt());
                builder.LoadFilterSegments(filter, author);
            }

            builder.SaveRouteSegments();
            return RedirectToAction("List", builder.CurrentRoute);
        }
    }   
}

Bookstore/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";

    var current = ViewContext.RouteData.Values["controller"]?.ToString();
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<ul class="nav nav-tabs mt-2 mb-3">
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Book"
           class="nav-link @Nav.Active("Book", current)">
            Manage Books
        </a>
    </li>
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Author"
           class="nav-link @Nav.Active("Author", current)">
            Manage Authors
        </a>
    </li>
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Genre"
           class="nav-link @Nav.Active("Genre", current)">
            Manage Genres
        </a>
    </li>
    <li class="nav-item">
        <a asp-action="Index" asp-controller="User"
           class="nav-link @Nav.Active("User", current)">
            Manage Users
        </a>
    </li>
</ul>

@RenderBody()